INSERT INTO category (id, label, email_address, address, dtype) VALUES (nextval('hibernate_sequence'), 'County Government of Makueni', 'contact@makueni.go.ke', '78 - 9300 - Makueni', 'ProcuringEntity');
INSERT INTO category (id, label, email_address, address, dtype) VALUES (nextval('hibernate_sequence'), 'Wote Municipality Board', 'wotemunicipality@gmail.com', '79 - 9300 - Makueni', 'ProcuringEntity');

INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'ACACIA RESORT', '146586', 'P.O.BOX 32   - 90300', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'ACCESS KENYA GROUP LIMITED', '34270', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'ACHELIS KENYA LIMITED', '148527', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'ACHELIS MATERIAL HANDLING LIMITED', '21716', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'AFRICA NAZARENE UNIVERSITY', '11217', 'P.O BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'AFRICAN  CAPITAL LIMITED', '20371', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'AFRICAN CAPITAL LIMITED', '11947', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'AGA KHAN UNIVERSITY HOSPITAL', '48677', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'AGNES MULEI', '111532', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'AIC KIJABE HOSPITAL', '73233', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'AIG KENYA INSURANCE COMPANY LIMITED', '40544', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'AIRTEL NETWORKS KENYA LIMITED', '26948', 'MAKUENI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'ALICE ATIENO BUSERA', '23589', 'P.O BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'ANEDA GENERAL AGENCIES', '142283', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'ANTELA INVESTMENTS', '83798', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'APA LIFE ASSURANCE LIMITED', '2238', 'MAKUENI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'ASHDOWN LIMITED', '125242', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'ASSOCIATION OF MEDICAL RECORDS OFFICERS', '25477', 'MAKUENI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'ASSOCIATION OF PROFESSIONAL SOCIETIES IN EAST AFRICA', '96664', 'P.O. BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'ATHLETICS KENYA', '47733', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'ATLAS COPCO EASTERN AFRICA LIMITED', '55661', 'P.O. BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'BANCO AGENCIES', '12290', 'PO BOX 11270 NAIROBI NAIROBI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'BARCLAYS BANK KENYA LIMITED', '25752', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'BEADLES LIMITED', '120689', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'BELFAST ENGINEERING WORKS LIMITED', '89271', '59242', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'BENTHA ENTERPRISES LIMITED', '12795', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'BEQUINS GENERAL ENTERPRISES', '123382', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'BLUE LIMITED KENYA', '44870', 'P.O.NAIROBI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'BLUE SCOPE CONTRACTORS', '145430', 'P.O. BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'BRANCO FURNITURES', '148251', 'p o box 10453 nairobi', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'BRANOLD ENTERPRISES', '148256', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'BRIGHT TECHNOLOGIES LIMITED', '97586', 'P.O BOX 19706   - 00100', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'BRITISH AMERICAN INSURANCE CO K LTD', '369140', 'p.o box 30375  nairobi - 00100', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'BRITISH AMERICAN INSURANCE COMPANY K LIMITED', '6121', 'PO BOX 572- WOTE   - 90300', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'BUDGET FURNITURE LIMITED', '72971', 'P.O BOX 34438   - 00100', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'BUREAU VERITAS KENYA LIMITED', '86683', 'MAKUENI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'CAPHI ENTERPRISES', '148041', 'P.O.BOX 40362', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'CAPM STATIONERS', '139710', 'KARACHI HOUSE P.O BOX 55097  NAIROBI - 00200', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'CENTRAL FARMERS GARAGE LIMITED', '114747', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'CFC STANBIC BANK KENYA  LIMITED', '21073', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'CHAKOPENKA GENERAL SUPPLIERS LIMITED', '146870', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'CHEMOQUIP LIMITED', '45296', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'CIC INSURANCE GROUP LIMITED', '10268', ' PO BOX   - 00100', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'CIVIL SERVANTS HOUSING FUND SCHEME', '17380', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'CMC MOTORS GROUP LIMITED', '101', ' P.O.NAIROBI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'COLLEGE OF INSURANCE', '1129', 'NAIROBI P.O. BOX 56928   - 00200', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'COPIER SOLUTIONS AND TECHNOLOGIES LIMITED', '118820', 'parliarment road embassy P.O BOX 36324  - 00200', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'CORPORATE INSURANCE COMPANY LIMITED', '7566', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'CREDIBLE SOUNDS', '59902', 'P.O BOX 32155   - 00600', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'DANNGA SERVICES LIMITED', '15855', ' PO', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'DAVIS AND SHIRTLIFF LIMITED', '19778', ' MAKUENI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'DERBY POINT ENTERPRISES', '142270', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'DIGICOM NETWORKS', '62496', 'P.O BOX 13674 INTERMARK BUSINESS CENTRE TAVETA ROAD  NAIROBI - 00800', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'DIMENSIONAL SERVICES LIMITED', '131867', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'DOABLE CONCEPTS AND DECO', '114997', 'NAIROBI P.O. BOX 6932   - 00300', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'DOCIE GENERAL SUPPLIERS', '31548', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'DOCKS INVESTMENTS AND SUPPLIES COMPANY LIMITED', '49765', ' MAKUENI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'DOREK OFFICE SUPPLIES', '2145', 'P.O BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'DOUBLE FOUR SUPPLIES', '84405', 'MAKUENI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'DUNCAN MWANGANGI MUIA', '140333', 'P.O BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'EASTERN BROADCASTING CORPORATION LIMITED', '58959', ' P.O. BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'ELBURGON VENTURES LIMITED', '146168', ' MAKUENI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'ELFORD MERCHANTS', '145428', 'P.O BOX 8712  NAIROBI - 00200', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'EMU INYA ENTERPRISES LIMITED', '69328', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'EPTON ENTERPRISES', '16002', 'P.O BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'ESRI EASTERN AFRICA', '70167', 'PO BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'ESTELLE DISTRIBUTORS', '97857', 'PO BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'EXXON TECHNOLOGIES', '129761', 'P.O BOX 8114  NAIROBI - 00200', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'FAMILY BANK LIMITED', '7678', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'FARAM EAST AFRICA LIMITED', '62332', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'FINE TOUCH COMMUNICATIONS LIMITED', '21473', ' MAKUENI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'FINELYNX ENTERPRISES', '102055', 'POBOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'FINETOPS ENTERPRISES LIMITED', '9871', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'FIRSTLING SUPPLIES LIMITED', '28696', ' P. O. BOX 8906 NAIROBI   - 00200', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'FLEXIFIELD ENTERPRISES', '22271', 'P.O. BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'FORCES EQUIPMENT K LIMITED', '11829', ' P.O BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'FRAJOPA PRINTERS MALL', '61113', 'PO BOX 572- WOTE', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'FRONTAL ENTERPRISES LIMITED', '133216', 'P.O. BOX 24256 ACCRA ROAD  NAIROBI - 00100', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'GARDEN HOTEL MACHAKOS LIMITED', '107408', ' MAKUENI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'GATWICK TECH ENTERPRISES LIMITED', '125949', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'GENERAL MOTORS EAST AFRICA LIMITED', '4693', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'GESTALT GILD LIMITED', '89193', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'GETRUDES CHILDRENS HOSPITAL', '60926', 'P.O BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'GOLDEDGE SUPPLIERS', '145429', 'MAKUENI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'GREAT GRACE AGENCIES', '15863', 'P.O BOX 9894   - 00200', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'GREEN PARK GOLF  AND COUNTRY COMPLEX LIMITED', '113345', ' P.O BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'HAPOLS ENTERPRISES', '148250', 'VISION PLAZA   - 29891-00200', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'HARAMBEE SAVINGS AND CREDIT COOPERATIVE SOCIETY', '258', 'NAIROBI P.O. BOX 47815   - 00100', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'HURUMA WOMEN GROUP', '139520', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'INSTITUTE FOR CAPACITY DEVELOPMENT', '145708', 'BOX 2521 00621', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'ISOVYA YOUTH POLYTECHNIC', '100568', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'JANROSE ENTERPRISE AND SUPPLIERS', '141006', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'JODAM E.A LIMITED', '113726', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'JUBILEE INSURANCE COMPANY OF KENYA LIMITED', '2240', 'NAIROBI P.O. BOX 30376   - 00100', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'JUNIAN ENTERPRISES', '22789', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KAKUSWI YOUTH POLYTECHNIC', '110905', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KALZMAT SECURITY PRINT LIMITED', '7338', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KAPWELL ENTERPRISES  LIMITED', '85413', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KASYALA INVESTMENTs LIMITED', '137501', ' P.O BOX 28431 NAIROBI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KATHONZWENI YOUTH POLYTECHNIC', '100560', 'MAKUENI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KATUTECH FAIR PRIZES', '135691', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KENTAINERS LIMITED', '7077', ' P.O. BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KENYA ACCOUNTANTS AND SECRETARIES NATIONAL EXAMINATION BOARD', '4790', 'MAKUENI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KENYA AGRICULTURAL RESEARCH INSTITUTE', '7630', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KENYA ASSOCIATION OF LIVESTOCK TECHNICIAN', '29600', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KENYA ASSOCIATION OF RADIOGRAPHY', '25479', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KENYA BROADCASTING CORPORATION', '1541', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KENYA COMMERCIAL  BANK LIMITED', '26826', ' PO BOX 572- WOTE   - 90137', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KENYA COMMERCIAL BANK  LIMITED', '2121', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KENYA FORESTRY RESEARCH INSTITUTE', '36279', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KENYA HOSPITAL ASSOCIATION', '47168', 'P.O BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KENYA MANAGEMENT AND TRAINING CONSULTANTS', '528', 'MAKUENI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KENYA MEDICAL PRACTITIONERS PHARMARCISTS AND DENTISTS UNION', '143719', 'NAIROBI P.O. BOX 157   - 00202', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KENYA METHODIST UNIVERSITY', '4158', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KENYA NATIONAL SECRETARIES ASSOCIATION', '102963', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KENYA PLASTERS ASSOCIATION', '25484', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KENYA POST OFFICE SAVINGS BANK', '21068', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KENYA POWER AND LIGHTING COMPANY LIMITED', '1022', ' P.O.NAIROBI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KENYA RED CROSS SOCIETY', '129540', 'P.O. BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KENYA SAFARI LODGES AND HOTELS', '38525', 'PO BOX 90414   - 80100', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KENYA SCHOOL OF GOVERNMENT EMBU', '11397', 'P.O BOX402 60100 EMBU', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KENYA SCHOOL OF MONETARY STUDIES', '1659', 'P.O BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KENYA SOCIETY OF PHYSIOTHERAPISTS', '25485', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KENYATTA  NATIONAL HOSPITAL', '25589', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KENYATTA MATIBABU SACCO', '25473', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KENYATTA UNIVERSITY NORTH COAST BEACH HOTEL', '104589', 'P.O. BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KEW CREATIONS LIMITED', '10626', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KITALE KILIMO STAFF SELF HELP GROUP', '7656', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KITUI TEACHERS SACCO LIMITED', '19756', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KONNEXION SYSTEMS LIMITED', '104385', ' MAKUENI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KUKOPESHA KENYA LIMITED', '22658', 'NAIROBI P.O.BOX 55466   - 00200', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'KYULULINE ENTERPRISES', '134321', 'P.O BOX 73966   - 00200', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'LAYTON INTERNATIONAL SUPPLIES', '145427', 'P.O BOX 53361  NAIROBI - 00200', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'LEGIS POLICY ASSOCIATES', '109886', '70728   - 00400', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'LETSHEGO KENYA LIMITED', '128378', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'LIZSOL CHEM COMPANY LIMITED', '101279', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'MACHAKOS UNIVERSITY COLLEGE', '146059', 'P.O. BOX 136 KONZA/WOTE ROAD   - 90100', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'MAKUENI YOUTH POLYTECHNIC', '100565', 'MAKUENI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'MARAWAYS TOURS TRAVEL LIMITED', '24420', ' P.O BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'MARONY TRAVEL AGENCIES', '145938', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'MARSON INTERGRATED LIMITED', '142934', ' P.O. BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'MAWE-NA-ANDU COMPANY LIMITED', '146208', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'MAZINGIRA WELFARE AND SPORTS ASSOCIATION', '1374', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'MEDIAMAX NETWORK LIMITED', '110464', ' P.O BOX 103618   - 00100', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'MEDIPHARM E.A. LIMITED', '67006', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'MFI DOCUMENT SOLUTIONS LIMITED', '91', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'MIMA BOOKS LIMITED', '40392', ' PO BOX 27622 NAIRIBI   - 0100', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'MODERN DATA CABLES TECHNOLOGIES LIMITED', '128116', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'MOI TEACHING AND REFERRAL HOSPITAL', '13552', 'MAKUENI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'MOMBASA BEACH HOTEL', '19072', 'P.O BOX 90414   - 80100', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'MWALIMU SAVINGS AND CREDIT COOPERATIVE SOCIETY LIMITED', '2229', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'NAIMA ENTERPRISES', '39422', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'NAIROBI PROVINCIAL CO-OPERATIVE OFFICE', '57793', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'NATION MEDIA GROUP LIMITED', '73', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'NATIONAL ASSOCIATION FOR ORTHOPAEDIC TECHNOLOGISTS', '25487', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'NATIONAL BANK', '7628', 'P.O. BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'NATIONAL INDUSTRIAL TRAINING AUTHORITY', '5811', 'PO BOX 572- WOTE   - 90137', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'NATIONAL SOCIAL SECURITY FUND', '2914', 'PO BOX 572- WOTE   - 90137', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'NATRON ENTERPRISES', '114994', '21   - 90200', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'NATSAH ENTERPRISES', '135899', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'NEWFORTIS SAVINGS AND CREDIT COOPERATIVE SOCIETY LIMITED', '6674', ' MAKUENI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'NGAO CREDIT LIMITED', '139429', ' P.O. BOX 60776   - 00200', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'NGETHA YOUTH POLYTECHNIC', '142247', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'NYALI SUN AFRICA BEACH HOTEL', '101073', 'P.O. BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'OFFICE TECHNOLOGIES LIMITED', '1171', ' P.O. BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'OLD MUTUAL LIFE ASSURANCE COMPANY LIMITED', '106093', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'PAKAKAK TECHNOLOGIES', '131375', 'P.O BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'PAN AFRICAN LIFE ASSURANCE LIMITED', '7008', ' PO BOX   - 00100', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'PATULA ENTERPRISES', '93110', 'P.O BOX 25489,0721 250 73', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'PHARMACEUTICAL SOCIETY OF KENYA', '147874', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'PINNACLE BUSINESS SCHOOL LIMITED', '24883', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'PIONEER ASSURANCE COMPANY LIMITED', '17305', ' PO BOX   - 00100', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'PLATINUM CREDIT LIMITED', '371', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'PONELA KENYA LIMITED', '108800', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'POPULAR GENERAL SUPPLIERS', '60435', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'POSTAL CORPORATION OF KENYA', '11176', 'PO BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'POTENTIAL CONSULTANTS COMPANY LIMITED', '128099', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'SIZEMADO SERVICES', '135665', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'SMOOTHTEL AND DATA SOLUTIONS LIMITED', '12090', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'STANDARD GROUP LIMITED', '29054', ' MAKUENI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'STEM TEC LIMITED', '148925', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'STEP AUTO TYRES & ACCESSORIES', '67678', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'STIRLING CONSULTANTS', '81521', 'MAKUENI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'STRATHMORE UNIVERSITY BUSINESS SCHOOL', '50237', 'PO', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'SUBARU KENYA', '25990', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'SUNSET HOTEL LIMITED', '12588', ' p.o box 215', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'SWIFTCODE GLOBAL ENTERPRISES', '136807', 'P.O BOX 60580  NAIROBI - 00200', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'TECHNOLOGY ASSOCIATES (EA) LIMITED', '50241', ' CHIROMO RD  NAIROBI - P.O BOX 43457', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'TELEDATA TECHNOLOGIES LIMITED', '29326', ' P.O.BOX 40826', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'TELKOM KENYA LIMITED', '1108', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'TENTNOLOGY AND DECOR LIMITED', '112275', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'THE AUTOMOBILE ASSOCIATION OF KENYA', '4089', 'P.O BOX 40087   - 00100', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'THE HERITAGE INSURANCE COMPANY LIMITED', '116858', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'THE INSTITUTE OF CERTIFIED PUBLIC SECRETARIES OF KENYA', '1411', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'THE KENYAN ALLIANCE INSURANCE COMPANY LIMITED', '10257', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'THE MONARCH INSURANCE COMPANY LIMITED', '52443', ' MAKUENI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'THE PEOPLE MEDIA GROUP LIMITED', '250', ' P.O BOX 24943   - 000100', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'THE STANDARD GROUP LIMITED', '132', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'TIBYATEC SYSTEMS', '111062', 'NAKU FEEDS PLAZA P.O.BOX 10684 JOGOO ROAD NAIROBI - 00200', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'TILE AND CARPET CENTRE LIMITED', '1013', ' P.O. BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'TOTAL KENYA LIMITED', '15353', 'PO BOX 30736 TOTAL KENYA LIMITED   - 00100', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'TOYOTA KENYA  LIMITED', '503', ' p.o box 82048   - 80100', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'TRANS NATION SACCO LIMITED', '11742', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'TRAVELLERS BEACH HOTEL', '5880', 'PO BOX 572', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'TRIZA INVESTMENTS', '113575', 'P.O. BOX 60132  NAIROBI  ', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'UAP PROVINCIAL INSURANCE COMPANY', '47777', 'P.O. BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'UFUNDI SACCO', '10087', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'UKULIMA  SACCO SOCIETY LIMITED', '21979', 'NAIROBI P.O. BOX 44071   - 00100', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'UNION OF KENYA CIVIL SERVANTS', '7672', 'NAIROBI P.O. BOX 48083   - 00100', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'UPPER HILL SCHOOL', '109016', 'P.O BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'VAITOO ENTERPRISES', '141887', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'VEKARIA AUTO GARAGE LIMITED', '128467', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'VICTORIA FURNITURES LIMITED', '748', ' P.O BOX 10827   - 00400', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'VINFACE GENERAL AGENCIES LIMITED', '135202', '"P.O.BOX 56702-00200 BURUBURU MESORA MUMIAS STREET,  NAIROBI  "', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'VISION 2030 DELIVERY SECRETARIAT', '106276', 'P.O BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'VISION INSTITUTE OF PROFESSIONALS', '6158', 'MAKUENI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'WAMBUA KAWIVE', '142177', 'MAKUENI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'WANAANGA SAVINGS AND CREDIT COOPERATIVE SOCIETY LIMITED', '7491', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'WATER RESOURCES MANAGEMENT AUTHORITY', '3577', 'MAKUENI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'WATER WELFARE ASSOCIATION', '15690', 'MAKUENI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'WATERWELL INTERNATIONAL K LIMITED', '143243', ' P.O. BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'WAVELINE COMMERCIAL ENTERPRISES', '133784', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'WELLSCON LIMITED', '131306', ' MAKUENI', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'WINCOMP SERVICES LIMITED', '16318', ' P.O. BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'WIPER DEMOCRATIC MOVEMENT-KENYA (WDM-K)', '145609', 'PO BOX 572- WOTE   - 90137', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'WOODVENTURE KENYA LIMITED', '3404', 'NAIROBI P.O.BOX 52932   - 00202', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'WOTE TECHNICAL TRAINING INSTITUTE', '99110', 'P.O. BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'WOTE WATER AND SEWERAGE COMPANY', '138148', 'P.O.BOX', 'Supplier');
INSERT INTO category (id, label, code, address, dtype) VALUES (nextval('hibernate_sequence'), 'WOTECH KENYA LIMITED', '115130', 'P.O.BOX', 'Supplier');
