INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Ngaamba', (select id from category where dtype = 'Ward' and label = 'Kiima Kiu/Kalanzoni'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Malili', (select id from category where dtype = 'Ward' and label = 'Kiima Kiu/Kalanzoni'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kiou', (select id from category where dtype = 'Ward' and label = 'Kasikeu'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kasikeu', (select id from category where dtype = 'Ward' and label = 'Kasikeu'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Mukaa', (select id from category where dtype = 'Ward' and label = 'Mukaa'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kitaingo', (select id from category where dtype = 'Ward' and label = 'Mukaa'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Tulimani', (select id from category where dtype = 'Ward' and label = 'Tulimani'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kalawani', (select id from category where dtype = 'Ward' and label = 'Tulimani'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kathulumbi', (select id from category where dtype = 'Ward' and label = 'Kalawa'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kalawa', (select id from category where dtype = 'Ward' and label = 'Kalawa'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kiteta', (select id from category where dtype = 'Ward' and label = 'Kisau/Kiteta'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kisau', (select id from category where dtype = 'Ward' and label = 'Kisau/Kiteta'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kako', (select id from category where dtype = 'Ward' and label = 'Kako/Waia'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Waia', (select id from category where dtype = 'Ward' and label = 'Kako/Waia'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Nzeveni/Kyuu', (select id from category where dtype = 'Ward' and label = 'Mbooni'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Mbooni', (select id from category where dtype = 'Ward' and label = 'Mbooni'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kitundu/Utangwa', (select id from category where dtype = 'Ward' and label = 'Kithungo'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kithungo' , (select id from category where dtype = 'Ward' and label = 'Kithungo'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kilungu', (select id from category where dtype = 'Ward' and label = 'Ilima'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Ilima', (select id from category where dtype = 'Ward' and label = 'Ilima'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Luani', (select id from category where dtype = 'Ward' and label = 'Ukia'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Ukia', (select id from category where dtype = 'Ward' and label = 'Ukia'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kikoko', (select id from category where dtype = 'Ward' and label = 'Kilungu'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kithembe', (select id from category where dtype = 'Ward' and label = 'Kilungu'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Watema', (select id from category where dtype = 'Ward' and label = 'Kee'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kee/Kivani', (select id from category where dtype = 'Ward' and label = 'Kee'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kathonzweni', (select id from category where dtype = 'Ward' and label = 'Kathonzweni'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Mbuvo', (select id from category where dtype = 'Ward' and label = 'Kathonzweni'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kitise', (select id from category where dtype = 'Ward' and label = 'Kitise/Kithuki'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kithuki', (select id from category where dtype = 'Ward' and label = 'Kitise/Kithuki'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kithumani/Kyemundu', (select id from category where dtype = 'Ward' and label = 'Mbitini'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Mutyambua', (select id from category where dtype = 'Ward' and label = 'Mbitini'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kalamba', (select id from category where dtype = 'Ward' and label = 'Nzaui/Kalamba'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Nzaui', (select id from category where dtype = 'Ward' and label = 'Nzaui/Kalamba'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kikumini', (select id from category where dtype = 'Ward' and label = 'Muvau'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Muvau', (select id from category where dtype = 'Ward' and label = 'Muvau'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Mavindini', (select id from category where dtype = 'Ward' and label = 'Mavindini'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kanthuni', (select id from category where dtype = 'Ward' and label = 'Mavindini'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Wote', (select id from category where dtype = 'Ward' and label = 'Wote'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Nziu', (select id from category where dtype = 'Ward' and label = 'Wote'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kambu', (select id from category where dtype = 'Ward' and label = 'Mtito Andei'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Mtito Andei', (select id from category where dtype = 'Ward' and label = 'Mtito Andei'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Nzambani', (select id from category where dtype = 'Ward' and label = 'Ivingoni'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Nthongoni', (select id from category where dtype = 'Ward' and label = 'Ivingoni'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Utithi', (select id from category where dtype = 'Ward' and label = 'Thange'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kinyambu', (select id from category where dtype = 'Ward' and label = 'Thange'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kyumani', (select id from category where dtype = 'Ward' and label = 'Masongaleni'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Mukaange' , (select id from category where dtype = 'Ward' and label = 'Masongaleni'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Makindu', (select id from category where dtype = 'Ward' and label = 'Makindu'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kiboko/Twaandu', (select id from category where dtype = 'Ward' and label = 'Makindu'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Mikuyuni/Mbui Nzau', (select id from category where dtype = 'Ward' and label = 'Kikumbulyu South'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kalungu/Nganda', (select id from category where dtype = 'Ward' and label = 'Kikumbulyu South'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kunguni/Muuni', (select id from category where dtype = 'Ward' and label = 'Nguumo'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Syumile/Ndovoini', (select id from category where dtype = 'Ward' and label = 'Nguumo'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Mulala', (select id from category where dtype = 'Ward' and label = 'Emali/Mulala'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Emali', (select id from category where dtype = 'Ward' and label = 'Emali/Mulala'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Nguu', (select id from category where dtype = 'Ward' and label = 'Nguu/Masumba'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Masumba', (select id from category where dtype = 'Ward' and label = 'Nguu/Masumba'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kathyaka/Ndetani', (select id from category where dtype = 'Ward' and label = 'Kikumbulyu North'), 'SubWard');
INSERT INTO category (id, label, ward_id, dtype) VALUES (nextval('hibernate_sequence'), 'Ngulu', (select id from category where dtype = 'Ward' and label = 'Kikumbulyu North'), 'SubWard');