INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Tulimani', (select id from category where dtype = 'Subcounty' and label = 'Mbooni'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Mbooni', (select id from category where dtype = 'Subcounty' and label = 'Mbooni'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kithungo', (select id from category where dtype = 'Subcounty' and label = 'Mbooni'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kisau/Kiteta', (select id from category where dtype = 'Subcounty' and label = 'Mbooni'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kako/Waia', (select id from category where dtype = 'Subcounty' and label = 'Mbooni'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kalawa', (select id from category where dtype = 'Subcounty' and label = 'Mbooni'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kiima Kiu/Kalanzoni', (select id from category where dtype = 'Subcounty' and label = 'Kilome'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Mukaa', (select id from category where dtype = 'Subcounty' and label = 'Kilome'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kasikeu', (select id from category where dtype = 'Subcounty' and label = 'Kilome'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kee', (select id from category where dtype = 'Subcounty' and label = 'Kaiti'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kilungu', (select id from category where dtype = 'Subcounty' and label = 'Kaiti'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Ilima', (select id from category where dtype = 'Subcounty' and label = 'Kaiti'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Ukia', (select id from category where dtype = 'Subcounty' and label = 'Kaiti'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Nzaui/Kalamba', (select id from category where dtype = 'Subcounty' and label = 'Makueni'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Muvau', (select id from category where dtype = 'Subcounty' and label = 'Makueni'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kathonzweni', (select id from category where dtype = 'Subcounty' and label = 'Makueni'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Mavindini', (select id from category where dtype = 'Subcounty' and label = 'Makueni'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kitise/Kithuki' , (select id from category where dtype = 'Subcounty' and label = 'Makueni'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Wote', (select id from category where dtype = 'Subcounty' and label = 'Makueni'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Mbitini', (select id from category where dtype = 'Subcounty' and label = 'Makueni'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Makindu', (select id from category where dtype = 'Subcounty' and label = 'Kibwezi West'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kikumbulyu North', (select id from category where dtype = 'Subcounty' and label = 'Kibwezi West'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Kikumbulyu South', (select id from category where dtype = 'Subcounty' and label = 'Kibwezi West'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Nguumo', (select id from category where dtype = 'Subcounty' and label = 'Kibwezi West'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Nguu/Masumba', (select id from category where dtype = 'Subcounty' and label = 'Kibwezi West'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Emali/Mulala', (select id from category where dtype = 'Subcounty' and label = 'Kibwezi West'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Masongaleni', (select id from category where dtype = 'Subcounty' and label = 'Kibwezi East'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Mtito Andei', (select id from category where dtype = 'Subcounty' and label = 'Kibwezi East'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Thange', (select id from category where dtype = 'Subcounty' and label = 'Kibwezi East'), 'Ward');
INSERT INTO category (id, label, subcounty_id, dtype) VALUES (nextval('hibernate_sequence'), 'Ivingoni', (select id from category where dtype = 'Subcounty' and label = 'Kibwezi East'), 'Ward');